### ISSUE TITLE
Metrics are published with a timestamp of several minutes in the future

### ISSUE THREAD

**Issue by juanrh** [aws-robotics/cloudwatchmetrics-ros1#10]
When processing `MetricList` messages we convert the nanoseconds time on the metrics `time_stamp` to milliseconds incorrectly. Instead of dividing by `1000000` [we divide by `1000`](https://github.com/aws-robotics/cloudwatchmetrics-ros1/blob/ad347e3b847c7ca7738250230025d351f3a91855/cloudwatch_metrics_collector/src/cloudwatch_metrics_collector.cpp#L75). As a result metrics are sent to CloudWatch metrics with a time stamp displaced to the future. 

We will send a patch to fix this bug to have this fixed in the next two days

**Comment by juanrh** [comment]
The code fix was merged to the master and release-v1 branches. We are keeping this issue open until the fix is also available in our Apt packages

**Comment by juanrh** [comment]
The code fix was merged to the master and release-v1 branches. We are keeping this issue open until the fix is also available in our Apt packages

**Comment by AAlon** [comment]
The fixed version is now available in apt.
