### ISSUE TITLE
Cloudwatch_metrics_collector launching but not publishing metrics

### ISSUE THREAD

**Issue by maarufvazifdar** [aws-robotics/cloudwatchmetrics-ros1#65]
Hello, I want to monitor custom metrics of my robot on cloudwatch, when  I launch using  sample_application.launch it works. But when I use a launch file from a different package and include the cloudwatch_metrics_collector.launch file and provide arg for config file (same as in sample_application.launch), it doesn't work. Please help me with this issue.
@jpeddicord @dabonnie @mm318 @timrobotson

**Comment by dabonnie** [comment]
Hello @maarufvazifdar, sorry you're currently having issues! Could you please provide your launch file for us to review? @jikawa-az @emersonknapp please take a look.

**Comment by emersonknapp** [comment]
Like @dabonnie said - please provide your launchfile, and a copy-paste of the terminal output when it fails, we don't have quite enough information to help.

**Comment by maarufvazifdar** [comment]
Hi, I was publishing around 50 metrics so after increasing the  request_timeout_ms and connect_timeout_ms to 20 seconds it worked.
